<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>abstraction_cpp</name>
  <version>0.1.0</version>
  <description>AVDS Exercise 3 - Abstract base class interfaces in C++</description>
  <maintainer email="daniel.esser@tum.de">Daniel Esser</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
